language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.8.0'
rvm:
  - 2.2.0

notifications:
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
